version: '3.7'
services:
  web:
    image: vergissberlin/hugo-docker-watchtower
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      - VIRTUAL_HOST=${DOMAINS}
      - VIRTUAL_NETWORK=${NETWORK}
      - LETSENCRYPT_HOST=${DOMAINS}
      - LETSENCRYPT_EMAIL=info@andrelademann.de
